REM AUTHOR: WASIF ZAMAN
REM DATE_: 12.23.2014
REM PURPOSE: SHUTDOWN CLASSROOM COMPUTERS

shutdown /s /m \\LCCS-BEATLES-01
shutdown /s /m \\LCCS-BEATLES-02
shutdown /s /m \\LCCS-BEATLES-03
shutdown /s /m \\LCCS-BEATLES-04
shutdown /s /m \\LCCS-BEATLES-05
shutdown /s /m \\LCCS-BEATLES-06
shutdown /s /m \\LCCS-EARHART-01
shutdown /s /m \\LCCS-EARHART-02
shutdown /s /m \\LCCS-EARHART-03
shutdown /s /m \\LCCS-EARHART-04
shutdown /s /m \\LCCS-EARHART-05
shutdown /s /m \\LCCS-HAWKING-01
shutdown /s /m \\LCCS-HAWKING-02
shutdown /s /m \\LCCS-HAWKING-03
shutdown /s /m \\LCCS-HAWKING-04
shutdown /s /m \\LCCS-HAWKING-05
shutdown /s /m \\LCCS-MANDELA-01
shutdown /s /m \\LCCS-MANDELA-02
shutdown /s /m \\LCCS-MANDELA-03
shutdown /s /m \\LCCS-MANDELA-04
shutdown /s /m \\LCCS-MANDELA-05
shutdown /s /m \\LCCS-MOZART-01
shutdown /s /m \\LCCS-MOZART-02
shutdown /s /m \\LCCS-MOZART-03
shutdown /s /m \\LCCS-MOZART-04
shutdown /s /m \\LCCS-MOZART-05
shutdown /s /m \\LCCS-NEWTON-01
shutdown /s /m \\LCCS-NEWTON-02
shutdown /s /m \\LCCS-NEWTON-03
shutdown /s /m \\LCCS-NEWTON-04
shutdown /s /m \\LCCS-NEWTON-05
shutdown /s /m \\LCCS-PASCAL-01
shutdown /s /m \\LCCS-PASCAL-02
shutdown /s /m \\LCCS-PASCAL-03
shutdown /s /m \\LCCS-PASCAL-04
shutdown /s /m \\LCCS-PASCAL-05
shutdown /s /m \\LCCS-PLATO-01
shutdown /s /m \\LCCS-PLATO-02
shutdown /s /m \\LCCS-PLATO-03
shutdown /s /m \\LCCS-PLATO-04
shutdown /s /m \\LCCS-PLATO-05
shutdown /s /m \\LCCS-SEUSS-01
shutdown /s /m \\LCCS-SEUSS-02
shutdown /s /m \\LCCS-SEUSS-03
shutdown /s /m \\LCCS-SEUSS-04
shutdown /s /m \\LCCS-SEUSS-05
shutdown /s /m \\LCCS-TERESA-01
shutdown /s /m \\LCCS-TERESA-02
shutdown /s /m \\LCCS-TERESA-03
shutdown /s /m \\LCCS-TERESA-04
shutdown /s /m \\LCCS-TERESA-05
shutdown /s /m \\LCCS-TESLA-01
shutdown /s /m \\LCCS-TESLA-02
shutdown /s /m \\LCCS-TESLA-03
shutdown /s /m \\LCCS-TESLA-04
shutdown /s /m \\LCCS-TESLA-05
shutdown /s /m \\LCCS-WILDE-01
shutdown /s /m \\LCCS-WILDE-02
shutdown /s /m \\LCCS-WILDE-03
shutdown /s /m \\LCCS-WILDE-04
shutdown /s /m \\LCCS-WILDE-05