REM AUTHOR: WASIF ZAMAN
REM DATE_: 12.23.2014
REM PURPOSE: RESTART LAB MACHINES

shutdown /r /m \\LCCS-LAB-001
shutdown /r /m \\LCCS-LAB-002
shutdown /r /m \\LCCS-LAB-003
shutdown /r /m \\LCCS-LAB-004
shutdown /r /m \\LCCS-LAB-005
shutdown /r /m \\LCCS-LAB-006
shutdown /r /m \\LCCS-LAB-007
shutdown /r /m \\LCCS-LAB-008
shutdown /r /m \\LCCS-LAB-009
shutdown /r /m \\LCCS-LAB-010
shutdown /r /m \\LCCS-LAB-011
shutdown /r /m \\LCCS-LAB-012
shutdown /r /m \\LCCS-LAB-013
shutdown /r /m \\LCCS-LAB-014
shutdown /r /m \\LCCS-LAB-015
shutdown /r /m \\LCCS-LAB-016
shutdown /r /m \\LCCS-LAB-017
shutdown /r /m \\LCCS-LAB-018
shutdown /r /m \\LCCS-LAB-019
shutdown /r /m \\LCCS-LAB-020
shutdown /r /m \\LCCS-LAB-021
shutdown /r /m \\LCCS-LAB-022
shutdown /r /m \\LCCS-LAB-023
shutdown /r /m \\LCCS-LAB-024
shutdown /r /m \\LCCS-LAB-025
shutdown /r /m \\LCCS-LAB-026
shutdown /r /m \\LCCS-LAB-027
shutdown /r /m \\LCCS-LAB-028
shutdown /r /m \\LCCS-LAB-029
shutdown /r /m \\LCCS-LAB-030
shutdown /r /m \\LCCS-LAB-031
shutdown /r /m \\LCCS-LAB-032
shutdown /r /m \\LCCS-LAB-033
shutdown /r /m \\LCCS-LAB-034
shutdown /r /m \\LCCS-LAB-035
shutdown /r /m \\LCCS-LAB-036
shutdown /r /m \\LCCS-LAB-037
shutdown /r /m \\LCCS-LAB-038
shutdown /r /m \\LCCS-LAB-039
shutdown /r /m \\LCCS-LAB-040
shutdown /r /m \\LCCS-LAB-041
shutdown /r /m \\LCCS-LAB-042
shutdown /r /m \\LCCS-LAB-043
shutdown /r /m \\LCCS-LAB-044
shutdown /r /m \\LCCS-LAB-045
shutdown /r /m \\LCCS-LAB-046